### ISSUE TITLE
Trouble passing -co arguments

### ISSUE THREAD

**Issue by claytonrothschild** [indus/kubi#12] opened 2023-09-11 18:05 UTC
Great library, thank you.

When I pass co arguments on linux and mac, Pyvips fails. Mac and linux.

Any tips greatly appreciated.

`kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co overlap=0`

```
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument overlap
```

`kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co jpg`

```
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument compression
```

**Comment by indus** [comment] 2023-09-11 18:54
Havn't looked into this but maybe it helps to move the -co before the input and output?!Am 11.09.2023 20:05 schrieb Clayton Rothschild ***@***.***>:
Great library, thank you.
When I pass co arguments on linux and mac, Pyvips fails. Mac and linux.
Any tips greatly appreciated.
kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co overlap=0
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument overlap

kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co jpg
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument compression

**Comment by indus** [comment] 2023-09-11 18:58
Oh wait I think it clearly says what the problem is those options are not supported fo jpeg. Compresdion is available for tiffs for example (you can use jpeg compresdion in a tiff or lzw or something else). The overlap option is only available for deepzoom (.dz) image pyramids.So I would say the errors are correct.Am 11.09.2023 20:05 schrieb Clayton Rothschild ***@***.***>:
Great library, thank you.
When I pass co arguments on linux and mac, Pyvips fails. Mac and linux.
Any tips greatly appreciated.
kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co overlap=0
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument overlap

kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co jpg
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument compression

**Comment by indus** [comment] 2023-09-11 19:02
Here is a list of the options for jpegsave: https://libvips.github.io/pyvips/vimage.html#pyvips.Image.jpegsaveMaybe you wanted "Q" for quality?Am 11.09.2023 20:05 schrieb Clayton Rothschild ***@***.***>:
Great library, thank you.
When I pass co arguments on linux and mac, Pyvips fails. Mac and linux.
Any tips greatly appreciated.
kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co overlap=0
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument overlap

kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co jpg
Traceback (most recent call last):
  File "/usr/local/bin/kubi", line 33, in <module>
    sys.exit(load_entry_point('kubi', 'console_scripts', 'kubi')())
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 343, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 339, in main
    kubi(args)
  File "/usr/local/lib/python3.9/site-packages/kubi/kubi.py", line 225, in kubi
    mapim.write_to_file(f'{dst}_{fn}{dst_ext}', **args.co)
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 804, in write_to_file
    return pyvips.Operation.call(name, self, filename,
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignSaveJpegFile does not support optional argument compression

**Comment by indus** [comment] 2023-09-14 19:29
@claytonrothschild Were you able to solve the problems and generate the desired output with kubi? Should I close this?

**Comment by claytonrothschild** [comment] 2023-09-15 14:14
The solution is that indeed the -co arguments fail if one is not generating an image pyramid (`dzsave`) - as those arguments are specific to image pyramid. 

Details [here](https://github.com/libvips/libvips/blob/master/doc/Making-image-pyramids.md)

So for example, this will fail:

```
kubi -r lbb -f nx px py ny nz pz test.jpg test_out.jpg -co overlap=0
```

but this will succeed no problem:

```
kubi -r lbb -f nx px py ny nz pz test.jpg test_out.dz -co overlap=0
```

We can close this!

**Closed** 2023-09-16 19:16 UTC
